[package]
name = "rust"
version = "0.1.0"
authors = ["Namiki Shimoo <naminori4mo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
